language: node_js

node_js:
  - 'node'
  - 'lts/*'

addons:
    code_climate:
        repo_token: a2f3968e958f60ab4ac0bd1a99651b8a9aad8d46b9dda61f5ff82bc2adbb292e

script:
  - npm run test:coverage
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm install codeclimate-test-reporter istanbul -g

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules